spring:
  application:
    name: service-order
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.188:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yaml
#        prefix: service-web
